# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo.xci
# IP: The module: 'axis_bridge_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo/axis_bridge_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_bridge_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo/axis_bridge_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_bridge_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo.xci
# IP: The module: 'axis_bridge_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo/axis_bridge_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_bridge_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.srcs/sources_1/ip/axis_bridge_fifo/axis_bridge_fifo/axis_bridge_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_bridge_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
