# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/PROJECT_2017/SSTANDARD/RTL/kc705/kc705_sdi_pcie_170117/ip_repo/clk_div_by2/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/PROJECT_2017/SSTANDARD/RTL/kc705/kc705_sdi_pcie_170117/ip_repo/clk_div_by2/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/PROJECT_2017/SSTANDARD/RTL/kc705/kc705_sdi_pcie_170117/ip_repo/clk_div_by2/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/PROJECT_2017/SSTANDARD/RTL/kc705/kc705_sdi_pcie_170117/ip_repo/clk_div_by2/clk_div_by2.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top clk_div_by2 -part xc7k325tffg900-1


write_checkpoint -force -noxdef clk_div_by2.dcp

catch { report_utilization -file clk_div_by2_utilization_synth.rpt -pb clk_div_by2_utilization_synth.pb }
