# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/system_ila_0_2.xci
# IP: The module: 'system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/system_ila_0_2.xci
# IP: The module: 'system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_HDMI_IN_OUT/system/system.srcs/sources_1/bd/system/ip/system_ila_0_2/system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
