# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xq7z030rf676-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/p_2017/sstandard_2/icb/rtl/icb_system_170719/ip_repo/v_in_crop_scale_axis
  e:/p_2017/sstandard_2/icb/rtl/icb_system_170710/ip_repo/v_in_crop_scale_axis
} [current_project]
set_property ip_output_repo e:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.runs/axis_bridge_fifo_synth_1/axis_bridge_fifo.dcp
set_property used_in_implementation false [get_files E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/project_1/project_1.runs/axis_bridge_fifo_synth_1/axis_bridge_fifo.dcp]
read_verilog -library xil_defaultlib E:/P_2017/SSTANDARD_2/ICB/RTL/icb_system_170719/ip_repo/v_in_crop_scale_axis/v_in_crop_scale_axis.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top v_in_crop_scale_axis -part xq7z030rf676-1Q


write_checkpoint -force -noxdef v_in_crop_scale_axis.dcp

catch { report_utilization -file v_in_crop_scale_axis_utilization_synth.rpt -pb v_in_crop_scale_axis_utilization_synth.pb }
