# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/clk_sel/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/clk_sel/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/clk_sel [current_project]
set_property ip_output_repo e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/clk_sel/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/clk_sel/clk_4_1_sel.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top clk_4_1_sel -part xc7k325tffg900-2


write_checkpoint -force -noxdef clk_4_1_sel.dcp

catch { report_utilization -file clk_4_1_sel_utilization_synth.rpt -pb clk_4_1_sel_utilization_synth.pb }
