set_property PACKAGE_PIN G15 [get_ports {pl_switch_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_switch_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_switch_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_switch_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_switch_tri_i[0]}]
set_property PACKAGE_PIN P15 [get_ports {pl_switch_tri_i[1]}]
set_property PACKAGE_PIN W13 [get_ports {pl_switch_tri_i[2]}]
set_property PACKAGE_PIN T16 [get_ports {pl_switch_tri_i[3]}]

set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p]

set_property PACKAGE_PIN T11 [get_ports TMDS_User_clk_p]
set_property PACKAGE_PIN T12 [get_ports {TMDS_User_data_p[0]}]
set_property PACKAGE_PIN V15 [get_ports {TMDS_User_data_p[1]}]
set_property PACKAGE_PIN W14 [get_ports {TMDS_User_data_p[2]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
