# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xq7z030rf676-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SSTD2/ICB/RTL/2nd/SEU/icb_seu_vso_2nd_171130/ip_repo/v_in_duplicate/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SSTD2/ICB/RTL/2nd/SEU/icb_seu_vso_2nd_171130/ip_repo/v_in_duplicate/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/P_2017/SSTD2/ICB/RTL/2nd/SEU/icb_seu_vso_2nd_171130/ip_repo/v_in_duplicate/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/P_2017/SSTD2/ICB/RTL/2nd/SEU/icb_seu_vso_2nd_171130/ip_repo/v_in_duplicate/v_in_duplicate.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top v_in_duplicate -part xq7z030rf676-1Q


write_checkpoint -force -noxdef v_in_duplicate.dcp

catch { report_utilization -file v_in_duplicate_utilization_synth.rpt -pb v_in_duplicate_utilization_synth.pb }
