# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller
  e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axilite_sdlc_controller
  e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axi_sdlc_controller
  e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/sdlc_controller
} [current_project]
set_property ip_output_repo e:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/project_1/project_1.srcs/sources_1/imports/core/utility.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/crc.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/fifo.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/utility.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/sfr.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/transmit.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/receive.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/top/dualram.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/top/axi_streaming_dma_rx_fifo.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/top/axi_streaming_dma_tx_fifo.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/top/axi_ctrlif.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/core/sdlc.vhd
  E:/P_2017/SEEDCORE/RTL/V16_3/mcb_axis_sdlc_170327/ip_repo/axis_sdlc_controller/src/top/axis_sdlc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top AXIS_SDLC -part xc7z020clg484-2


write_checkpoint -force -noxdef AXIS_SDLC.dcp

catch { report_utilization -file AXIS_SDLC_utilization_synth.rpt -pb AXIS_SDLC_utilization_synth.pb }
