# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/vid_in_24b_axis_ngc.v
  E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/vid_in_24b_axis.v
}
read_edif E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/vid_in_24b_axis/vid_in_24b_axis_ngc.edn
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top vid_in_24b_axis -part xc7z035ffg676-2


write_checkpoint -force -noxdef vid_in_24b_axis.dcp

catch { report_utilization -file vid_in_24b_axis_utilization_synth.rpt -pb vid_in_24b_axis_utilization_synth.pb }
