# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z045ffg900-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw
  e:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/project_1/project_1.srcs/sources_1/new
} [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/axis_s2_m1_sw_ngc.v
  E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/axis_s2_m1_sw.v
}
read_edif E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/axis_s2_m1_sw/axis_s2_m1_sw_ngc.edn
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top axis_s2_m1_sw -part xc7z045ffg900-3


write_checkpoint -force -noxdef axis_s2_m1_sw.dcp

catch { report_utilization -file axis_s2_m1_sw_utilization_synth.rpt -pb axis_s2_m1_sw_utilization_synth.pb }
