# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z030ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/rs170_std_out_ctrl/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/rs170_std_out_ctrl/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  e:/p_2017/seedcore/sim/user_ip_repo/rs170_std_out_ctrl
  e:/p_2017/seedcore/sim/rs170_out_ctrl
} [current_project]
set_property ip_output_repo e:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/rs170_std_out_ctrl/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/rs170_std_out_ctrl/rs170_std_out_ctrl.vhd
read_edif E:/P_2017/SEEDCORE/RTL/FINAL/mcb_rel_1.0_170509/ip_repo/rs170_std_out_ctrl/rs170_std_out_ctrl_ngc.edn
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top rs170_std_out_ctrl -part xc7z030ffg676-2


write_checkpoint -force -noxdef rs170_std_out_ctrl.dcp

catch { report_utilization -file rs170_std_out_ctrl_utilization_synth.rpt -pb rs170_std_out_ctrl_utilization_synth.pb }
